language: go

sudo: false

go:
    - 1.4
    - tip

before_install:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/modocache/gover
    - go get github.com/mattn/goveralls

script:
    - go test ./...
    - gover
    - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile  -service=travis-ci 

